# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    article_admin:
      quality: 75
      filters:
        thumbnail:
          size: [100, 75]
          mode: outbound
    coin_admin:
      quality: 75
      filters:
        thumbnail:
          size: [100, 75]
          mode: outbound
    sport:
      quality: 75
      filters:
        thumbnail:
          size: [350, 175]
          mode: outbound
    article:
      quality: 75
      filters:
        thumbnail:
          size: [328, 164]
          mode: outbound
    articleRecent:
      quality: 75
      filters:
        thumbnail:
          size: [548, 274]
          mode: outbound
